# Generated by Django 4.1.7 on 2023-04-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seller_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_fullname', models.CharField(max_length=50)),
                ('seller_username', models.EmailField(max_length=254, unique=True)),
                ('seller_password', models.CharField(max_length=50)),
            ],
        ),
    ]
