# Generated by Django 4.1.7 on 2023-04-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.FileField(default='anonymous.png', upload_to='media /'),
        ),
    ]
