# Generated by Django 4.1.7 on 2023-04-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.FileField(default='anonymous.png', max_length=254, upload_to='media /'),
        ),
    ]
