# Generated by Django 4.1.7 on 2023-04-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.FileField(default='anonymous.jfif', upload_to='media/'),
        ),
    ]
